openstudio_path: ../openstudioapplication-1.8.0/
EPlus_file: ../openstudioapplication-1.8.0/EnergyPlus
osm_name_box: ./sim_env/Final.osm
weather_data: ./weather_data/CHN_SH_Lang.Gang.Island.584760_TMYx.epw
iddfile: ./sim_env/Energy+.idd
save_idf: ./sim_env/run.idf
weight_file: ./weights/last.pth
replay_buffer: replay_buffer.pkl
HVAC_output: False
reset_dataframe: False
Train: True
signal_loss: False
Roof_Switch: off
RL_flag: True
timestep_per_hour: 1
FPS: 1000
positive_reward: 0
signal_factor: 0
T_factor_day: 1
T_factor_night: 0.1
E_factor_day: 1.0e-5
E_factor_night: 1.0e-5
L_factor: 1
T_bottom: 5
T_top: 50
